import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'vi';
  setLanguage: (lang: 'en' | 'vi') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.confirmPassword': 'Confirm Password',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.description': 'Description',
    'common.created': 'Created',
    'common.lastActive': 'Last Active',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.documents': 'Documents',
    'common.schools': 'Schools',
    'common.provinces': 'Provinces',
    'common.users': 'Users',
    
    // Auth
    'auth.login': 'Sign In',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.signIn': 'Sign in to your school account',
    'auth.registerSchool': 'Register your school',
    'auth.emailAddress': 'Email Address',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating Account...',
    'auth.newSchool': 'New school?',
    'auth.registerHere': 'Register here',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signInHere': 'Sign in here',
    'auth.demoAccounts': 'Demo accounts:',
    'auth.passwordAny': 'Password: any',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.chat': 'Chat',
    'nav.documents': 'Documents',
    'nav.schools': 'My Schools',
    'nav.provinces': 'Provinces',
    'nav.userManagement': 'User Management',
    'nav.systemTree': 'System Tree',
    'nav.documentStore': 'Document Store',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.schoolSubtitle': 'Manage your documents and chat with AI',
    'dashboard.provinceSubtitle': 'Monitor schools in your province',
    'dashboard.deputySubtitle': 'Oversee all educational institutions',
    'dashboard.aiAssistant': 'AI Assistant',
    'dashboard.askQuestions': 'Ask questions about your uploaded documents',
    'dashboard.manageDocuments': 'Manage Documents',
    'dashboard.totalProvinces': 'Total Provinces',
    'dashboard.totalSchools': 'Total Schools',
    'dashboard.totalDocuments': 'Total Documents',
    
    // Chat
    'chat.newChat': 'New Chat',
    'chat.chatHistory': 'Chat History',
    'chat.messages': 'messages',
    'chat.askQuestion': 'Ask a question about your documents...',
    'chat.aiCanMakeMistakes': 'AI can make mistakes. Verify important information from your documents.',
    'chat.hello': 'Hello! I\'m your AI assistant. I can help you find information from your uploaded documents. What would you like to know?',
    'chat.referencedDocuments': 'Referenced documents:',
    
    // Documents
    'documents.manager': 'Documents Manager',
    'documents.uploadAndManage': 'Upload and manage your documents for AI-powered Q&A',
    'documents.uploadDocuments': 'Upload Documents',
    'documents.manageDocuments': 'Manage Documents',
    'documents.dropFiles': 'Drop files here or click to browse',
    'documents.supportedFormats': 'Supports PDF, Word documents (.doc, .docx), and Excel files (.xls, .xlsx)',
    'documents.chooseFiles': 'Choose Files',
    'documents.uploading': 'Uploading...',
    'documents.recentUploads': 'Recent Uploads',
    'documents.searchDocuments': 'Search documents...',
    'documents.allStatus': 'All Status',
    'documents.ready': 'Ready',
    'documents.processing': 'Processing',
    'documents.error': 'Error',
    'documents.noDocuments': 'No documents found',
    'documents.tryAdjusting': 'Try adjusting your search or filter criteria',
    'documents.uploadFirst': 'Upload your first document to get started',
    'documents.tips': 'Tips for better results:',
    'documents.tip1': '• Upload clear, readable documents for optimal AI processing',
    'documents.tip2': '• Organize files with descriptive names',
    'documents.tip3': '• Documents go through advanced processing: text extraction, indexing, and AI optimization',
    'documents.tip4': '• Use the chat feature to ask questions about your uploaded content',
    'documents.tip5': '• Larger documents may take longer to process but provide more comprehensive results',
    
    // User Management
    'users.management': 'User Management',
    'users.manageAll': 'Manage all system users and their permissions',
    'users.createUser': 'Create User',
    'users.createNew': 'Create New User',
    'users.editUser': 'Edit User',
    'users.deleteUser': 'Delete User',
    'users.userDetails': 'User Details',
    'users.searchUsers': 'Search users by name or email...',
    'users.allRoles': 'All Roles',
    'users.deputy': 'Deputy',
    'users.province': 'Province',
    'users.school': 'School',
    'users.role': 'Role',
    'users.owner': 'Owner',
    'users.uploaded': 'Uploaded',
    'users.noUsers': 'No users found',
    'users.getStarted': 'Get started by creating your first user',
    'users.schoolName': 'School Name',
    'users.enterSchoolName': 'Enter school name',
    'users.enterSchoolEmail': 'Enter school email',
    'users.selectProvince': 'Select Province',
    'users.enterPassword': 'Enter password',
    'users.confirmPassword': 'Confirm password',
    'users.requiredFields': '* Required fields',
    'users.creatingAccount': 'Creating Account...',
    'users.createAccount': 'Create Account',
    'users.passwordsNotMatch': 'Passwords do not match',
    'users.passwordMinLength': 'Password must be at least 6 characters',
    'users.provinceRequired': 'Province is required for this role',
    'users.userCreated': 'User created successfully!',
    'users.userUpdated': 'User updated successfully!',
    'users.userDeleted': 'User deleted successfully!',
    'users.failedCreate': 'Failed to create user',
    'users.failedUpdate': 'Failed to update user',
    'users.failedDelete': 'Failed to delete user',
    'users.deleteWarning': 'This action cannot be undone. The user will lose access to their account and all associated data.',
    'users.deleteProvinceWarning': 'This will also affect all schools in this province.',
    'users.roleCannotChange': 'Role cannot be changed',
    'users.creating': 'Creating...',
    'users.updating': 'Updating...',
    'users.deleting': 'Deleting...',
    'users.saveChanges': 'Save Changes',
    'users.updateUser': 'Update User',
    'users.warning': 'Warning',
    
    // Schools Management
    'schools.management': 'Schools Management',
    'schools.manageInProvince': 'Manage schools in your province',
    'schools.addNewSchool': 'Add New School',
    'schools.addNew': 'Add New School',
    'schools.editSchool': 'Edit School',
    'schools.deleteSchool': 'Delete School',
    'schools.schoolDetails': 'School Details',
    'schools.searchSchools': 'Search schools by name or email...',
    'schools.noSchools': 'No schools found',
    'schools.getStartedSchool': 'Get started by adding your first school',
    'schools.principalName': 'Principal Name',
    'schools.enterPrincipalName': 'Enter principal\'s full name',
    'schools.enterPhoneNumber': 'Enter phone number',
    'schools.schoolAddress': 'School address',
    'schools.schoolCreated': 'School account created successfully!',
    'schools.importantNotes': 'Important Notes:',
    'schools.note1': '• The school will receive login credentials via email',
    'schools.note2': '• Schools can upload documents and use AI chat features',
    'schools.note3': '• You can monitor their activity from your province dashboard',
    'schools.note4': '• Schools can change their password after first login',
    'schools.deleteWarningSchool': 'Are you sure you want to delete this school? This action cannot be undone.',
    
    // Provinces Management
    'provinces.management': 'Provinces Management',
    'provinces.manageAll': 'Manage all provinces and their educational institutions',
    'provinces.addNewProvince': 'Add New Province',
    'provinces.addNew': 'Add New Province',
    'provinces.editProvince': 'Edit Province',
    'provinces.deleteProvince': 'Delete Province',
    'provinces.provinceDetails': 'Province Details',
    'provinces.searchProvinces': 'Search provinces by name...',
    'provinces.noProvinces': 'No provinces found',
    'provinces.getStartedProvince': 'Get started by adding your first province',
    'provinces.provinceName': 'Province Name',
    'provinces.enterProvinceName': 'Enter province name',
    'provinces.provinceManager': 'Province Manager Name',
    'provinces.enterManagerName': 'Enter manager\'s full name',
    'provinces.officeAddress': 'Office Address',
    'provinces.provinceOfficeAddress': 'Province office address',
    'provinces.briefDescription': 'Brief description about the province...',
    'provinces.provinceCreated': 'Province account created successfully!',
    'provinces.provinceNote1': '• The province manager will receive login credentials via email',
    'provinces.provinceNote2': '• Province managers can add and manage schools in their region',
    'provinces.provinceNote3': '• They can monitor all school activities and document uploads',
    'provinces.provinceNote4': '• Province accounts can change their password after first login',
    'provinces.deleteWarningProvince': 'Are you sure you want to delete this province? This will also delete all associated schools. This action cannot be undone.',
    
    // System Tree
    'systemTree.title': 'System Tree View',
    'systemTree.subtitle': 'Visual hierarchy of the entire educational system',
    'systemTree.organizationalStructure': 'Organizational Structure',
    'systemTree.deputy': 'Deputy',
    'systemTree.province': 'Province',
    'systemTree.school': 'School',
    
    // Document Store
    'documentStore.title': 'Document Store',
    'documentStore.subtitle': 'Centralized document management for all system users',
    'documentStore.searchDocuments': 'Search documents by name or owner...',
    'documentStore.allTypes': 'All Types',
    'documentStore.pdf': 'PDF',
    'documentStore.word': 'Word',
    'documentStore.excel': 'Excel',
    'documentStore.document': 'Document',
    'documentStore.deputyDocs': 'Deputy Docs',
    'documentStore.provinceDocs': 'Province Docs',
    'documentStore.schoolDocs': 'School Docs',
    'documentStore.totalSize': 'Total Size',
    
    // Language
    'language.english': 'English',
    'language.vietnamese': 'Tiếng Việt',
  },
  vi: {
    // Common
    'common.loading': 'Đang tải...',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.delete': 'Xóa',
    'common.edit': 'Sửa',
    'common.view': 'Xem',
    'common.create': 'Tạo',
    'common.search': 'Tìm kiếm',
    'common.filter': 'Lọc',
    'common.close': 'Đóng',
    'common.yes': 'Có',
    'common.no': 'Không',
    'common.name': 'Tên',
    'common.email': 'Email',
    'common.password': 'Mật khẩu',
    'common.confirmPassword': 'Xác nhận mật khẩu',
    'common.phone': 'Điện thoại',
    'common.address': 'Địa chỉ',
    'common.description': 'Mô tả',
    'common.created': 'Đã tạo',
    'common.lastActive': 'Hoạt động cuối',
    'common.status': 'Trạng thái',
    'common.actions': 'Hành động',
    'common.documents': 'Tài liệu',
    'common.schools': 'Trường học',
    'common.provinces': 'Tỉnh thành',
    'common.users': 'Người dùng',
    
    // Auth
    'auth.login': 'Đăng nhập',
    'auth.register': 'Đăng ký',
    'auth.logout': 'Đăng xuất',
    'auth.signIn': 'Đăng nhập vào tài khoản trường học',
    'auth.registerSchool': 'Đăng ký trường học của bạn',
    'auth.emailAddress': 'Địa chỉ Email',
    'auth.enterEmail': 'Nhập email của bạn',
    'auth.enterPassword': 'Nhập mật khẩu của bạn',
    'auth.signingIn': 'Đang đăng nhập...',
    'auth.creatingAccount': 'Đang tạo tài khoản...',
    'auth.newSchool': 'Trường học mới?',
    'auth.registerHere': 'Đăng ký tại đây',
    'auth.alreadyHaveAccount': 'Đã có tài khoản?',
    'auth.signInHere': 'Đăng nhập tại đây',
    'auth.demoAccounts': 'Tài khoản demo:',
    'auth.passwordAny': 'Mật khẩu: bất kỳ',
    
    // Navigation
    'nav.dashboard': 'Bảng điều khiển',
    'nav.chat': 'Trò chuyện',
    'nav.documents': 'Tài liệu',
    'nav.schools': 'Trường học của tôi',
    'nav.provinces': 'Tỉnh thành',
    'nav.userManagement': 'Quản lý người dùng',
    'nav.systemTree': 'Cây hệ thống',
    'nav.documentStore': 'Kho tài liệu',
    
    // Dashboard
    'dashboard.welcome': 'Chào mừng trở lại',
    'dashboard.schoolSubtitle': 'Quản lý tài liệu và trò chuyện với AI',
    'dashboard.provinceSubtitle': 'Giám sát các trường học trong tỉnh',
    'dashboard.deputySubtitle': 'Giám sát tất cả các cơ sở giáo dục',
    'dashboard.aiAssistant': 'Trợ lý AI',
    'dashboard.askQuestions': 'Đặt câu hỏi về tài liệu đã tải lên',
    'dashboard.manageDocuments': 'Quản lý tài liệu',
    'dashboard.totalProvinces': 'Tổng số tỉnh',
    'dashboard.totalSchools': 'Tổng số trường',
    'dashboard.totalDocuments': 'Tổng số tài liệu',
    
    // Chat
    'chat.newChat': 'Cuộc trò chuyện mới',
    'chat.chatHistory': 'Lịch sử trò chuyện',
    'chat.messages': 'tin nhắn',
    'chat.askQuestion': 'Đặt câu hỏi về tài liệu của bạn...',
    'chat.aiCanMakeMistakes': 'AI có thể mắc lỗi. Hãy xác minh thông tin quan trọng từ tài liệu của bạn.',
    'chat.hello': 'Xin chào! Tôi là trợ lý AI của bạn. Tôi có thể giúp bạn tìm thông tin từ các tài liệu đã tải lên. Bạn muốn biết gì?',
    'chat.referencedDocuments': 'Tài liệu tham khảo:',
    
    // Documents
    'documents.manager': 'Quản lý tài liệu',
    'documents.uploadAndManage': 'Tải lên và quản lý tài liệu cho Q&A được hỗ trợ bởi AI',
    'documents.uploadDocuments': 'Tải lên tài liệu',
    'documents.manageDocuments': 'Quản lý tài liệu',
    'documents.dropFiles': 'Thả tệp vào đây hoặc nhấp để duyệt',
    'documents.supportedFormats': 'Hỗ trợ PDF, tài liệu Word (.doc, .docx), và tệp Excel (.xls, .xlsx)',
    'documents.chooseFiles': 'Chọn tệp',
    'documents.uploading': 'Đang tải lên...',
    'documents.recentUploads': 'Tải lên gần đây',
    'documents.searchDocuments': 'Tìm kiếm tài liệu...',
    'documents.allStatus': 'Tất cả trạng thái',
    'documents.ready': 'Sẵn sàng',
    'documents.processing': 'Đang xử lý',
    'documents.error': 'Lỗi',
    'documents.noDocuments': 'Không tìm thấy tài liệu',
    'documents.tryAdjusting': 'Thử điều chỉnh tiêu chí tìm kiếm hoặc bộ lọc',
    'documents.uploadFirst': 'Tải lên tài liệu đầu tiên để bắt đầu',
    'documents.tips': 'Mẹo để có kết quả tốt hơn:',
    'documents.tip1': '• Tải lên tài liệu rõ ràng, dễ đọc để xử lý AI tối ưu',
    'documents.tip2': '• Sắp xếp tệp với tên mô tả',
    'documents.tip3': '• Tài liệu trải qua xử lý nâng cao: trích xuất văn bản, lập chỉ mục và tối ưu hóa AI',
    'documents.tip4': '• Sử dụng tính năng trò chuyện để đặt câu hỏi về nội dung đã tải lên',
    'documents.tip5': '• Tài liệu lớn hơn có thể mất nhiều thời gian xử lý nhưng cung cấp kết quả toàn diện hơn',
    
    // User Management
    'users.management': 'Quản lý người dùng',
    'users.manageAll': 'Quản lý tất cả người dùng hệ thống và quyền của họ',
    'users.createUser': 'Tạo người dùng',
    'users.createNew': 'Tạo người dùng mới',
    'users.editUser': 'Sửa người dùng',
    'users.deleteUser': 'Xóa người dùng',
    'users.userDetails': 'Chi tiết người dùng',
    'users.searchUsers': 'Tìm kiếm người dùng theo tên hoặc email...',
    'users.allRoles': 'Tất cả vai trò',
    'users.deputy': 'Phó giám đốc',
    'users.province': 'Tỉnh',
    'users.school': 'Trường học',
    'users.role': 'Vai trò',
    'users.owner': 'Chủ sở hữu',
    'users.uploaded': 'Đã tải lên',
    'users.noUsers': 'Không tìm thấy người dùng',
    'users.getStarted': 'Bắt đầu bằng cách tạo người dùng đầu tiên',
    'users.schoolName': 'Tên trường học',
    'users.enterSchoolName': 'Nhập tên trường học',
    'users.enterSchoolEmail': 'Nhập email trường học',
    'users.selectProvince': 'Chọn tỉnh',
    'users.enterPassword': 'Nhập mật khẩu',
    'users.confirmPassword': 'Xác nhận mật khẩu',
    'users.requiredFields': '* Trường bắt buộc',
    'users.creatingAccount': 'Đang tạo tài khoản...',
    'users.createAccount': 'Tạo tài khoản',
    'users.passwordsNotMatch': 'Mật khẩu không khớp',
    'users.passwordMinLength': 'Mật khẩu phải có ít nhất 6 ký tự',
    'users.provinceRequired': 'Tỉnh là bắt buộc cho vai trò này',
    'users.userCreated': 'Tạo người dùng thành công!',
    'users.userUpdated': 'Cập nhật người dùng thành công!',
    'users.userDeleted': 'Xóa người dùng thành công!',
    'users.failedCreate': 'Không thể tạo người dùng',
    'users.failedUpdate': 'Không thể cập nhật người dùng',
    'users.failedDelete': 'Không thể xóa người dùng',
    'users.deleteWarning': 'Hành động này không thể hoàn tác. Người dùng sẽ mất quyền truy cập vào tài khoản và tất cả dữ liệu liên quan.',
    'users.deleteProvinceWarning': 'Điều này cũng sẽ ảnh hưởng đến tất cả trường học trong tỉnh này.',
    'users.roleCannotChange': 'Không thể thay đổi vai trò',
    'users.creating': 'Đang tạo...',
    'users.updating': 'Đang cập nhật...',
    'users.deleting': 'Đang xóa...',
    'users.saveChanges': 'Lưu thay đổi',
    'users.updateUser': 'Cập nhật người dùng',
    'users.warning': 'Cảnh báo',
    
    // Schools Management
    'schools.management': 'Quản lý trường học',
    'schools.manageInProvince': 'Quản lý trường học trong tỉnh của bạn',
    'schools.addNewSchool': 'Thêm trường học mới',
    'schools.addNew': 'Thêm trường học mới',
    'schools.editSchool': 'Sửa trường học',
    'schools.deleteSchool': 'Xóa trường học',
    'schools.schoolDetails': 'Chi tiết trường học',
    'schools.searchSchools': 'Tìm kiếm trường học theo tên hoặc email...',
    'schools.noSchools': 'Không tìm thấy trường học',
    'schools.getStartedSchool': 'Bắt đầu bằng cách thêm trường học đầu tiên',
    'schools.principalName': 'Tên hiệu trưởng',
    'schools.enterPrincipalName': 'Nhập họ tên hiệu trưởng',
    'schools.enterPhoneNumber': 'Nhập số điện thoại',
    'schools.schoolAddress': 'Địa chỉ trường học',
    'schools.schoolCreated': 'Tạo tài khoản trường học thành công!',
    'schools.importantNotes': 'Ghi chú quan trọng:',
    'schools.note1': '• Trường học sẽ nhận thông tin đăng nhập qua email',
    'schools.note2': '• Trường học có thể tải lên tài liệu và sử dụng tính năng trò chuyện AI',
    'schools.note3': '• Bạn có thể giám sát hoạt động của họ từ bảng điều khiển tỉnh',
    'schools.note4': '• Trường học có thể thay đổi mật khẩu sau lần đăng nhập đầu tiên',
    'schools.deleteWarningSchool': 'Bạn có chắc chắn muốn xóa trường học này? Hành động này không thể hoàn tác.',
    
    // Provinces Management
    'provinces.management': 'Quản lý tỉnh thành',
    'provinces.manageAll': 'Quản lý tất cả tỉnh thành và các cơ sở giáo dục',
    'provinces.addNewProvince': 'Thêm tỉnh mới',
    'provinces.addNew': 'Thêm tỉnh mới',
    'provinces.editProvince': 'Sửa tỉnh',
    'provinces.deleteProvince': 'Xóa tỉnh',
    'provinces.provinceDetails': 'Chi tiết tỉnh',
    'provinces.searchProvinces': 'Tìm kiếm tỉnh theo tên...',
    'provinces.noProvinces': 'Không tìm thấy tỉnh',
    'provinces.getStartedProvince': 'Bắt đầu bằng cách thêm tỉnh đầu tiên',
    'provinces.provinceName': 'Tên tỉnh',
    'provinces.enterProvinceName': 'Nhập tên tỉnh',
    'provinces.provinceManager': 'Tên quản lý tỉnh',
    'provinces.enterManagerName': 'Nhập họ tên quản lý',
    'provinces.officeAddress': 'Địa chỉ văn phòng',
    'provinces.provinceOfficeAddress': 'Địa chỉ văn phòng tỉnh',
    'provinces.briefDescription': 'Mô tả ngắn về tỉnh...',
    'provinces.provinceCreated': 'Tạo tài khoản tỉnh thành công!',
    'provinces.provinceNote1': '• Quản lý tỉnh sẽ nhận thông tin đăng nhập qua email',
    'provinces.provinceNote2': '• Quản lý tỉnh có thể thêm và quản lý trường học trong khu vực',
    'provinces.provinceNote3': '• Họ có thể giám sát tất cả hoạt động của trường học và tải lên tài liệu',
    'provinces.provinceNote4': '• Tài khoản tỉnh có thể thay đổi mật khẩu sau lần đăng nhập đầu tiên',
    'provinces.deleteWarningProvince': 'Bạn có chắc chắn muốn xóa tỉnh này? Điều này cũng sẽ xóa tất cả trường học liên quan. Hành động này không thể hoàn tác.',
    
    // System Tree
    'systemTree.title': 'Xem cây hệ thống',
    'systemTree.subtitle': 'Phân cấp trực quan của toàn bộ hệ thống giáo dục',
    'systemTree.organizationalStructure': 'Cơ cấu tổ chức',
    'systemTree.deputy': 'Phó giám đốc',
    'systemTree.province': 'Tỉnh',
    'systemTree.school': 'Trường học',
    
    // Document Store
    'documentStore.title': 'Kho tài liệu',
    'documentStore.subtitle': 'Quản lý tài liệu tập trung cho tất cả người dùng hệ thống',
    'documentStore.searchDocuments': 'Tìm kiếm tài liệu theo tên hoặc chủ sở hữu...',
    'documentStore.allTypes': 'Tất cả loại',
    'documentStore.pdf': 'PDF',
    'documentStore.word': 'Word',
    'documentStore.excel': 'Excel',
    'documentStore.document': 'Tài liệu',
    'documentStore.deputyDocs': 'Tài liệu phó giám đốc',
    'documentStore.provinceDocs': 'Tài liệu tỉnh',
    'documentStore.schoolDocs': 'Tài liệu trường học',
    'documentStore.totalSize': 'Tổng dung lượng',
    
    // Language
    'language.english': 'English',
    'language.vietnamese': 'Tiếng Việt',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'vi'>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as 'en' | 'vi';
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'vi')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: 'en' | 'vi') => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};