import React, { createContext, useContext } from 'react';

interface LanguageContextType {
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: { [key: string]: string } = {
  // Common
  'common.loading': 'Đang tải...',
  'common.save': 'Lưu',
  'common.cancel': 'Hủy',
  'common.delete': 'Xóa',
  'common.edit': 'Sửa',
  'common.view': 'Xem',
  'common.create': 'Tạo',
  'common.search': 'Tìm kiếm',
  'common.filter': 'Lọc',
  'common.close': 'Đóng',
  'common.yes': 'Có',
  'common.no': 'Không',
  'common.name': 'Tên',
  'common.email': 'Email',
  'common.password': 'Mật khẩu',
  'common.confirmPassword': 'Xác nhận mật khẩu',
  'common.phone': 'Điện thoại',
  'common.address': 'Địa chỉ',
  'common.description': 'Mô tả',
  'common.created': 'Đã tạo',
  'common.lastActive': 'Hoạt động cuối',
  'common.status': 'Trạng thái',
  'common.actions': 'Hành động',
  'common.documents': 'Tài liệu',
  'common.schools': 'Trường học',
  'common.provinces': 'Tỉnh thành',
  'common.users': 'Người dùng',
  
  // Auth
  'auth.login': 'Đăng nhập',
  'auth.register': 'Đăng ký',
  'auth.logout': 'Đăng xuất',
  'auth.signIn': 'Đăng nhập vào tài khoản trường học',
  'auth.registerSchool': 'Đăng ký trường học của bạn',
  'auth.emailAddress': 'Địa chỉ Email',
  'auth.enterEmail': 'Nhập email của bạn',
  'auth.enterPassword': 'Nhập mật khẩu của bạn',
  'auth.signingIn': 'Đang đăng nhập...',
  'auth.creatingAccount': 'Đang tạo tài khoản...',
  'auth.newSchool': 'Trường học mới?',
  'auth.registerHere': 'Đăng ký tại đây',
  'auth.alreadyHaveAccount': 'Đã có tài khoản?',
  'auth.signInHere': 'Đăng nhập tại đây',
  'auth.demoAccounts': 'Tài khoản demo:',
  'auth.passwordAny': 'Mật khẩu: bất kỳ',
  
  // Navigation
  'nav.chat': 'Trò chuyện',
  'nav.documents': 'Tài liệu',
  'nav.schools': 'Trường học của tôi',
  'nav.provinces': 'Tỉnh thành',
  'nav.userManagement': 'Quản lý người dùng',
  'nav.systemTree': 'Cây hệ thống',
  'nav.documentStore': 'Kho tài liệu',
  
  // Chat
  'chat.newChat': 'Cuộc trò chuyện mới',
  'chat.chatHistory': 'Lịch sử trò chuyện',
  'chat.messages': 'tin nhắn',
  'chat.askQuestion': 'Đặt câu hỏi về tài liệu của bạn...',
  'chat.aiCanMakeMistakes': 'AI có thể mắc lỗi. Hãy xác minh thông tin quan trọng từ tài liệu của bạn.',
  'chat.hello': 'Xin chào! Tôi là trợ lý AI của bạn. Tôi có thể giúp bạn tìm thông tin từ các tài liệu đã tải lên. Bạn muốn biết gì?',
  'chat.referencedDocuments': 'Tài liệu tham khảo:',
  
  // Documents
  'documents.manager': 'Quản lý tài liệu',
  'documents.uploadAndManage': 'Tải lên và quản lý tài liệu cho Q&A được hỗ trợ bởi AI',
  'documents.uploadDocuments': 'Tải lên tài liệu',
  'documents.manageDocuments': 'Quản lý tài liệu',
  'documents.dropFiles': 'Thả tệp vào đây hoặc nhấp để duyệt',
  'documents.supportedFormats': 'Hỗ trợ tài liệu Word (.doc, .docx), và tệp Excel (.xls, .xlsx)',
  'documents.chooseFiles': 'Chọn tệp',
  'documents.uploading': 'Đang tải lên...',
  'documents.recentUploads': 'Tải lên gần đây',
  'documents.searchDocuments': 'Tìm kiếm tài liệu...',
  'documents.allStatus': 'Tất cả trạng thái',
  'documents.ready': 'Sẵn sàng',
  'documents.processing': 'Đang xử lý',
  'documents.error': 'Lỗi',
  'documents.noDocuments': 'Không tìm thấy tài liệu',
  'documents.tryAdjusting': 'Thử điều chỉnh tiêu chí tìm kiếm hoặc bộ lọc',
  'documents.uploadFirst': 'Tải lên tài liệu đầu tiên để bắt đầu',
  'documents.tips': 'Mẹo để có kết quả tốt hơn:',
  'documents.tip1': '• Tải lên tài liệu rõ ràng, dễ đọc để xử lý AI tối ưu',
  'documents.tip2': '• Sắp xếp tệp với tên mô tả',
  'documents.tip3': '• Tài liệu trải qua xử lý nâng cao: trích xuất văn bản, lập chỉ mục và tối ưu hóa AI',
  'documents.tip4': '• Sử dụng tính năng trò chuyện để đặt câu hỏi về nội dung đã tải lên',
  'documents.tip5': '• Tài liệu lớn hơn có thể mất nhiều thời gian xử lý nhưng cung cấp kết quả toàn diện hơn',
  
  // User Management
  'users.management': 'Quản lý người dùng',
  'users.manageAll': 'Quản lý tất cả người dùng hệ thống và quyền của họ',
  'users.createUser': 'Tạo người dùng',
  'users.createNew': 'Tạo người dùng mới',
  'users.editUser': 'Sửa người dùng',
  'users.deleteUser': 'Xóa người dùng',
  'users.userDetails': 'Chi tiết người dùng',
  'users.searchUsers': 'Tìm kiếm người dùng theo tên hoặc email...',
  'users.allRoles': 'Tất cả vai trò',
  'users.deputy': 'Phó giám đốc',
  'users.province': 'Tỉnh',
  'users.school': 'Trường học',
  'users.role': 'Vai trò',
  'users.owner': 'Chủ sở hữu',
  'users.uploaded': 'Đã tải lên',
  'users.noUsers': 'Không tìm thấy người dùng',
  'users.getStarted': 'Bắt đầu bằng cách tạo người dùng đầu tiên',
  'users.schoolName': 'Tên trường học',
  'users.enterSchoolName': 'Nhập tên trường học',
  'users.enterSchoolEmail': 'Nhập email trường học',
  'users.selectProvince': 'Chọn tỉnh',
  'users.enterPassword': 'Nhập mật khẩu',
  'users.confirmPassword': 'Xác nhận mật khẩu',
  'users.requiredFields': '* Trường bắt buộc',
  'users.creatingAccount': 'Đang tạo tài khoản...',
  'users.createAccount': 'Tạo tài khoản',
  'users.passwordsNotMatch': 'Mật khẩu không khớp',
  'users.passwordMinLength': 'Mật khẩu phải có ít nhất 6 ký tự',
  'users.provinceRequired': 'Tỉnh là bắt buộc cho vai trò này',
  'users.userCreated': 'Tạo người dùng thành công!',
  'users.userUpdated': 'Cập nhật người dùng thành công!',
  'users.userDeleted': 'Xóa người dùng thành công!',
  'users.failedCreate': 'Không thể tạo người dùng',
  'users.failedUpdate': 'Không thể cập nhật người dùng',
  'users.failedDelete': 'Không thể xóa người dùng',
  'users.deleteWarning': 'Hành động này không thể hoàn tác. Người dùng sẽ mất quyền truy cập vào tài khoản và tất cả dữ liệu liên quan.',
  'users.deleteProvinceWarning': 'Điều này cũng sẽ ảnh hưởng đến tất cả trường học trong tỉnh này.',
  'users.roleCannotChange': 'Không thể thay đổi vai trò',
  'users.creating': 'Đang tạo...',
  'users.updating': 'Đang cập nhật...',
  'users.deleting': 'Đang xóa...',
  'users.saveChanges': 'Lưu thay đổi',
  'users.updateUser': 'Cập nhật người dùng',
  'users.warning': 'Cảnh báo',
  
  // Schools Management
  'schools.management': 'Quản lý trường học',
  'schools.manageInProvince': 'Quản lý trường học trong tỉnh của bạn',
  'schools.addNewSchool': 'Thêm trường học mới',
  'schools.addNew': 'Thêm trường học mới',
  'schools.editSchool': 'Sửa trường học',
  'schools.deleteSchool': 'Xóa trường học',
  'schools.schoolDetails': 'Chi tiết trường học',
  'schools.searchSchools': 'Tìm kiếm trường học theo tên hoặc email...',
  'schools.noSchools': 'Không tìm thấy trường học',
  'schools.getStartedSchool': 'Bắt đầu bằng cách thêm trường học đầu tiên',
  'schools.principalName': 'Tên hiệu trưởng',
  'schools.enterPrincipalName': 'Nhập họ tên hiệu trưởng',
  'schools.enterPhoneNumber': 'Nhập số điện thoại',
  'schools.schoolAddress': 'Địa chỉ trường học',
  'schools.schoolCreated': 'Tạo tài khoản trường học thành công!',
  'schools.importantNotes': 'Ghi chú quan trọng:',
  'schools.note1': '• Trường học sẽ nhận thông tin đăng nhập qua email',
  'schools.note2': '• Trường học có thể tải lên tài liệu và sử dụng tính năng trò chuyện AI',
  'schools.note3': '• Bạn có thể giám sát hoạt động của họ từ bảng điều khiển tỉnh',
  'schools.note4': '• Trường học có thể thay đổi mật khẩu sau lần đăng nhập đầu tiên',
  'schools.deleteWarningSchool': 'Bạn có chắc chắn muốn xóa trường học này? Hành động này không thể hoàn tác.',
  
  // Provinces Management
  'provinces.management': 'Quản lý tỉnh thành',
  'provinces.manageAll': 'Quản lý tất cả tỉnh thành và các cơ sở giáo dục',
  'provinces.addNewProvince': 'Thêm tỉnh mới',
  'provinces.addNew': 'Thêm tỉnh mới',
  'provinces.editProvince': 'Sửa tỉnh',
  'provinces.deleteProvince': 'Xóa tỉnh',
  'provinces.provinceDetails': 'Chi tiết tỉnh',
  'provinces.searchProvinces': 'Tìm kiếm tỉnh theo tên...',
  'provinces.noProvinces': 'Không tìm thấy tỉnh',
  'provinces.getStartedProvince': 'Bắt đầu bằng cách thêm tỉnh đầu tiên',
  'provinces.provinceName': 'Tên tỉnh',
  'provinces.enterProvinceName': 'Nhập tên tỉnh',
  'provinces.provinceManager': 'Tên quản lý tỉnh',
  'provinces.enterManagerName': 'Nhập họ tên quản lý',
  'provinces.officeAddress': 'Địa chỉ văn phòng',
  'provinces.provinceOfficeAddress': 'Địa chỉ văn phòng tỉnh',
  'provinces.briefDescription': 'Mô tả ngắn về tỉnh...',
  'provinces.provinceCreated': 'Tạo tài khoản tỉnh thành công!',
  'provinces.provinceNote1': '• Quản lý tỉnh sẽ nhận thông tin đăng nhập qua email',
  'provinces.provinceNote2': '• Quản lý tỉnh có thể thêm và quản lý trường học trong khu vực',
  'provinces.provinceNote3': '• Họ có thể giám sát tất cả hoạt động của trường học và tải lên tài liệu',
  'provinces.provinceNote4': '• Tài khoản tỉnh có thể thay đổi mật khẩu sau lần đăng nhập đầu tiên',
  'provinces.deleteWarningProvince': 'Bạn có chắc chắn muốn xóa tỉnh này? Điều này cũng sẽ xóa tất cả trường học liên quan. Hành động này không thể hoàn tác.',
  
  // System Tree
  'systemTree.title': 'Xem cây hệ thống',
  'systemTree.subtitle': 'Phân cấp trực quan của toàn bộ hệ thống giáo dục',
  'systemTree.organizationalStructure': 'Cơ cấu tổ chức',
  'systemTree.deputy': 'Phó giám đốc',
  'systemTree.province': 'Tỉnh',
  'systemTree.school': 'Trường học',
  
  // Document Store
  'documentStore.title': 'Kho tài liệu',
  'documentStore.subtitle': 'Quản lý tài liệu tập trung cho tất cả người dùng hệ thống',
  'documentStore.searchDocuments': 'Tìm kiếm tài liệu theo tên hoặc chủ sở hữu...',
  'documentStore.allTypes': 'Tất cả loại',
  'documentStore.pdf': 'Tài liệu',
  'documentStore.word': 'Word',
  'documentStore.excel': 'Excel',
  'documentStore.document': 'Tài liệu',
  'documentStore.deputyDocs': 'Tài liệu phó giám đốc',
  'documentStore.provinceDocs': 'Tài liệu tỉnh',
  'documentStore.schoolDocs': 'Tài liệu trường học',
  'documentStore.totalSize': 'Tổng dung lượng',
  
  // Additional translations
  'documents.enterTitle': 'Nhập tiêu đề tài liệu',
  'documents.enterDescription': 'Nhập mô tả tài liệu',
  'documents.removeFile': 'Xóa tệp',
  'documents.view': 'Xem',
  'documents.download': 'Tải xuống',
  'documents.delete': 'Xóa',
  'auth.enterSchoolName': 'Nhập tên trường học',
  'auth.enterSchoolEmail': 'Nhập email trường học',
  'auth.confirmPassword': 'Xác nhận mật khẩu',
  'auth.createPassword': 'Tạo mật khẩu',
  'auth.confirmYourPassword': 'Xác nhận mật khẩu của bạn',
  'management.enterProvinceName': 'Nhập tên tỉnh',
  'management.enterProvinceManagerEmail': 'Nhập email quản lý tỉnh',
  'management.enterPasswordForProvinceManager': 'Nhập mật khẩu cho tài khoản quản lý tỉnh',
  'management.enterSchoolName': 'Nhập tên trường học',
  'management.enterSchoolEmail': 'Nhập email trường học',
  'management.enterPasswordForSchoolAccount': 'Nhập mật khẩu cho tài khoản trường học',
  'management.enterDepartmentId': 'Nhập ID phòng ban (tùy chọn)',
  'management.emailCannotBeUpdated': 'Email không thể cập nhật',
  'management.enterProvinceId': 'Nhập ID tỉnh',
  'management.enterNewEmail': 'Nhập email mới',
  
  // Document Management
  'documents.uploadDocument': 'Tải lên tài liệu',
  'documents.uploadStaffDocument': 'Tải lên tài liệu nhân viên',
  'documents.uploadStudentsDocument': 'Tải lên tài liệu học sinh',
  'documents.uploadExaminationsDocument': 'Tải lên tài liệu thi cử',
  'documents.exampleDocuments': 'Tài liệu mẫu',
  'documents.exampleDescription': 'Tải xuống các mẫu Excel để xem định dạng yêu cầu cho từng loại tài liệu.',
  'documents.staffTemplate': 'Mẫu nhân viên',
  'documents.studentsTemplate': 'Mẫu học sinh',
  'documents.examinationsTemplate': 'Mẫu thi cử',
  'documents.downloading': 'Đang tải xuống...',
  'documents.allTypes': 'Tất cả loại',
  'documents.general': 'Chung',
  'documents.staff': 'Nhân viên',
  'documents.students': 'Học sinh',
  'documents.examinations': 'Thi cử',
  
  // Upload Modal
  'documents.dropFileHere': 'Thả tệp vào đây',
  'documents.fileSelected': 'Tệp đã chọn',
  'documents.clickToBrowse': 'hoặc nhấp để duyệt tệp',
  'documents.supportsExcel': 'Hỗ trợ XLSX lên đến 10MB',
  'documents.documentTitleOptional': 'Tiêu đề tài liệu (Tùy chọn)',
  'documents.descriptionOptional': 'Mô tả (Tùy chọn)',
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const t = (key: string): string => {
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ t }}>
      {children}
    </LanguageContext.Provider>
  );
};